Copy and paste the following code into the if statement in the master stack-pack's dependency check function:
				
'mp_stacks_downloadgrid_textdomain' => 'mp-stacks-downloadgrid-check.php',
'mp_stacks_edd_textdomain' => 'mp-stacks-edd-check.php',
'mp_stacks_features_textdomain' => 'mp-stacks-features-check.php',
'mp_stacks_googlefonts_textdomain' => 'mp-stacks-googlefonts-check.php',
'mp_stacks_image_style_textdomain' => 'mp-stacks-image-style-check.php',
'mp_stacks_mailchimp_textdomain' => 'mp-stacks-mailchimp-check.php',
'mp_stacks_parallax_textdomain' => 'mp-stacks-parallax-check.php',
'mp_stacks_postgrid_textdomain' => 'mp-stacks-postgrid-check.php',
'mp_stacks_second_text_textdomain' => 'mp-stacks-second-text-check.php',
'mp_stacks_shadows_textdomain' => 'mp-stacks-shadows-check.php',
'mp_stacks_slider_textdomain' => 'mp-stacks-slider-check.php',
'mp_stacks_sociallinks_textdomain' => 'mp-stacks-sociallinks-check.php',
'mp_stacks_widgets_textdomain' => 'mp-stacks-widgets-check.php',
